// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyiqXtENHuYb7ZyeISOOdPBr7doA2fGu0',
    appId: '1:587641534406:web:8982a93209d0bbc9a164c7',
    messagingSenderId: '587641534406',
    projectId: 'fir-exercise-67a4f',
    authDomain: 'fir-exercise-67a4f.firebaseapp.com',
    storageBucket: 'fir-exercise-67a4f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6I9Tvl2uGD2tYjKr2F-wLrL2nCFsIPa4',
    appId: '1:587641534406:android:baec92474eae6472a164c7',
    messagingSenderId: '587641534406',
    projectId: 'fir-exercise-67a4f',
    storageBucket: 'fir-exercise-67a4f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDT8akJLixbAEPQnO8zxaRHkzbKbZYbjac',
    appId: '1:587641534406:ios:faa78fe2bfb4f3fca164c7',
    messagingSenderId: '587641534406',
    projectId: 'fir-exercise-67a4f',
    storageBucket: 'fir-exercise-67a4f.appspot.com',
    iosClientId: '587641534406-82koskq24chdae9un318ofionng1j6hc.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseExercise',
  );
}
